name: build_and_publish_image

on:
  push:
    branches:
      - master

jobs:
  build_and_publish_image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env:
      IMAGE_NAME: raspios-epgstation
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: 'l3tnun/EPGStation'

      - name: Copy Dockerfile
        run: cp Dockerfile.debian Dockerfile

      - name: Fix Dockerfile
        run: |
          sed -i -e "s@FROM --platform=\$BUILDPLATFORM@FROM@" Dockerfile || true
          sed -i -e "s@node:16-buster-slim@ghcr.io/longkey1/raspios-node:16-lite-arm64@" Dockerfile || true
          sed -i -e "s@node:16-buster@ghcr.io/longkey1/raspios-node:16-lite-arm64@" Dockerfile || true
          sed -i -e "s@^EXPOSE 8888$@i RUN apt-get install -y ffmpeg@" Dockerfile || true

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:arm64
          platforms: linux/arm64
