name: Publish Debian EPGStaion FFmpeg Image

on: workflow_dispatch

jobs:
  setup:
    name: Setup Outputs
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.settimestamp.outputs.timestamp }}
    steps:
      - name: Set timestamp output
        id: settimestamp
        env:
          TZ: 'Asia/Tokyo'
        run: echo "timestamp=$(date +'%Y%m%d')" >> ${GITHUB_OUTPUT}

  publish_epgstation_ffmpeg:
    name: Publish Epgstation FFmpeg Image
    needs:
      - setup
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./debian-epgstation-ffmpeg
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/epgstation:debian-epgstation-ffmpeg
            ghcr.io/${{ github.repository_owner }}/epgstation:debian-epgstation-ffmpeg-${{ needs.setup.outputs.timestamp }}
