name: Publish Raspios64 EPGStaion Image

on: workflow_dispatch

jobs:
  setup:
    name: Setup Outputs
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.settimestamp.outputs.timestamp }}
    steps:
      - name: Set timestamp output
        id: settimestamp
        env:
          TZ: 'Asia/Tokyo'
        run: echo "timestamp=$(date +'%Y%m%d')" >> $GITHUB_ENV

  publish_epgstation:
    name: Publish EPGStation Image
    needs:
      - setup
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: 'l3tnun/EPGStation'

      - name: Copy Dockerfile
        run: cp Dockerfile.debian Dockerfile

      - name: Fix Dockerfile
        run: |
          sed -i -e "s@FROM --platform=\$BUILDPLATFORM@FROM@" Dockerfile
          sed -i -e "s@node:16-buster-slim@ghcr.io/longkey1/raspios-node:16-lite-arm64@" Dockerfile
          sed -i -e "s@node:16-buster@ghcr.io/longkey1/raspios-node:16-lite-arm64@" Dockerfile

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/epgstation:raspios64-epgstation
            ghcr.io/${{ github.repository_owner }}/epgstation:raspios64-epgstation-${{ needs.setup.outputs.timestamp }}
          platforms: linux/arm64
